In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import sys, copy, emcee, corner

%matplotlib inline
%load_ext autoreload

sys.path.append('./ligbind/')
import ligbind as lb

In [2]:
WT_08_lbl, WT_08_rtot, WT_08_lig, WT_08_sat = lb.datprep('Data/EGFR_WT_08_Sat.csv','Data/EGFR_WT_08_Rtot.csv')
WT_09_lbl, WT_09_rtot, WT_09_lig, WT_09_sat = lb.datprep('Data/EGFR_WT_09_Sat.csv','Data/EGFR_WT_09_Rtot.csv')
WT_11_lbl, WT_11_rtot, WT_11_lig, WT_11_sat = lb.datprep('Data/EGFR_WT_11_Sat.csv','Data/EGFR_WT_11_Rtot.csv')

hootie hoo! the indices match!
hootie hoo! the indices match!
hootie hoo! the indices match!


In [3]:
def rtot_objfun(guess,parm,lig,dat):
    datac = np.concatenate(dat)
    calc = lb.models.wymfunc(parm,lig,guess)
    
    return (calc-datac)
    

In [6]:
guess = np.array([0.001,0.003,0.005,0.01,0.02,0.03])

In [9]:
parms = np.array([4.6,5.3,0.34,530.])

In [10]:
rtot_objfun(guess,parms,WT_08_lig,WT_08_sat)

array([-0.0164731 , -0.01895512, -0.00647369, -0.00612299,  0.01836136,
       -0.00126613,  0.02603005,  0.07466845, -0.01253466, -0.028678  ,
        0.00590562,  0.00553225,  0.03186777,  0.01713015, -0.01526264,
       -0.0022922 , -0.00641707,  0.00243886,  0.00644122,  0.01103878,
       -0.01484492, -0.0207233 , -0.03069195, -0.00204195,  0.01633407,
       -0.01352036,  0.00581783, -0.01328738, -0.01068824,  0.01964022,
        0.03023312,  0.00553165, -0.01489492, -0.00225757,  0.0014237 ,
       -0.04222487, -0.03772394, -0.04308389,  0.00134986, -0.02185199,
       -0.00199387, -0.01193571,  0.00547358,  0.00751177, -0.01913387,
       -0.03247373, -0.04477795, -0.08669428, -0.06406837, -0.0833117 ,
       -0.01738786, -0.03897044, -0.02901607,  0.01722956, -0.01416308,
       -0.00240049,  0.01300474, -0.0168107 , -0.01791408, -0.00374973,
       -0.01035836, -0.03640324, -0.01008158, -0.00174584, -0.04702937,
       -0.01063256, -0.01438064, -0.00430402, -0.01462584, -0.00

In [17]:
lsbnds = (tuple(1e-5 for i in range(6)),tuple(1e-1 for i in range(6)))

In [18]:
a = sp.optimize.least_squares(rtot_objfun,guess,args=(parms,WT_08_lig,WT_08_sat),bounds=lsbnds)

In [19]:
a.x

array([ 0.00143878,  0.00242228,  0.00339179,  0.0027181 ,  0.01216361,
        0.02594478])

In [20]:
WT_08_rtot

array([ 0.001439,  0.002422,  0.003392,  0.002718,  0.01216 ,  0.02594 ])

In [21]:
WT_09_lig.shape

(5,)

In [22]:
WT_11_rtot.shape

(6,)

In [23]:
a = sp.optimize.least_squares(rtot_objfun,guess,args=(parms,WT_11_lig,WT_11_sat),bounds=lsbnds)

In [24]:
a.x

array([ 0.00330977,  0.00679375,  0.01122675,  0.09999999,  0.1       ,
        0.1       ])