In [1]:
import numpy as np

In [2]:
kratios = np.array([0.1,1.,10.])
lratios = np.array([10.,100.,1000.])
coopmags = np.array([10.,100.,1000.])

In [3]:
base = 5.

In [4]:
[[base, base*kratios[i],(base*kratios[i])/4.,base*lratios[i]] for i in range(3)]

[[5.0, 0.5, 0.125, 50.0], [5.0, 5.0, 1.25, 500.0], [5.0, 50.0, 12.5, 5000.0]]

In [7]:
[[base, base*kratios[i],(base*kratios[i])*coopmags[i],base*lratios[i]] for i in range(3)]

[[5.0, 0.5, 5.0, 50.0], [5.0, 5.0, 500.0, 500.0], [5.0, 50.0, 50000.0, 5000.0]]

In [15]:
terb = np.array([[base*i for i in kratios],[base for i in range(3)]])

In [16]:
terb

array([[  0.5,   5. ,  50. ],
       [  5. ,   5. ,   5. ]])

In [17]:
terb[0]

array([  0.5,   5. ,  50. ])

In [18]:
inds = range(3)
[[base for i in range(3)],[base*kratio[i] for i in range]]

TypeError: 'type' object is not iterable

In [19]:
def maker(base):
    kratios = np.array([0.1,1.,10.])
    lratios = np.array([10.,100.,1000.])
    coopmags = np.array([10.,100.,1000.])
    temp = np.array([base,base,base,base])
    return temp*np.array([1.,1.,0.25,10.])

In [20]:
maker(5)

array([  5.  ,   5.  ,   1.25,  50.  ])

In [35]:
hold = np.ones(shape=(5,4))

In [36]:
hold

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [37]:
hold[:,0]=5

In [38]:
hold

array([[ 5.,  1.,  1.,  1.],
       [ 5.,  1.,  1.,  1.],
       [ 5.,  1.,  1.,  1.],
       [ 5.,  1.,  1.,  1.],
       [ 5.,  1.,  1.,  1.]])

In [39]:
hold[:,1]=(5.*0.1)

In [41]:
hold[:,2]=hold[:,1]/4.

In [42]:
hold

array([[ 5.   ,  0.5  ,  0.125,  1.   ],
       [ 5.   ,  0.5  ,  0.125,  1.   ],
       [ 5.   ,  0.5  ,  0.125,  1.   ],
       [ 5.   ,  0.5  ,  0.125,  1.   ],
       [ 5.   ,  0.5  ,  0.125,  1.   ]])

In [43]:
from itertools import product

In [72]:
arrays = [[5.,], [50.,5.,0.5], [5000,]]

In [73]:
cp = list(product(*arrays))

In [74]:
cp

[(5.0, 50.0, 5000), (5.0, 5.0, 5000), (5.0, 0.5, 5000)]

In [75]:
np.array(cp)

array([[  5.00000000e+00,   5.00000000e+01,   5.00000000e+03],
       [  5.00000000e+00,   5.00000000e+00,   5.00000000e+03],
       [  5.00000000e+00,   5.00000000e-01,   5.00000000e+03]])

In [143]:
base = np.array([5.,])
k2s = np.array([0.1,1.,10.])*base
k21s = np.array([1000.,100.,10.,0.1,0.01,0.001])*base
ls = np.array([10.,100.,1000.])*base

In [144]:
things = [base,k2s,k21s,ls]

In [145]:
b = list(product(*things))

In [146]:
len(b)

54

In [103]:
a = set(b)

In [147]:
len(a)

54

In [148]:
c = np.array(b)

In [149]:
h = c.tolist()

In [118]:
c[:,2]=c[:,1]/4.

In [130]:
neuts = np.array(list(set([tuple(i.tolist()) for i in c])))

In [125]:
[tuple(i.tolist()) for i in c]

[(5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 0.5, 0.125, 50.0),
 (5.0, 0.5, 0.125, 500.0),
 (5.0, 0.5, 0.125, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 5.0, 1.25, 50.0),
 (5.0, 5.0, 1.25, 500.0),
 (5.0, 5.0, 1.25, 5000.0),
 (5.0, 50.0, 12.5, 50.0),
 (5.0, 50.0, 12.5, 5

In [129]:
c

array([[  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+01],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+02],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+03],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+01],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+02],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+03],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+01],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+02],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+03],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+01],
       [  5.00000000e+00,   5.00000000e-01,   1.25000000e-01,
          5.00000000e+02],
       [  5.00000000e

In [137]:
all_sets = np.concatenate([c,neuts])

In [133]:
type(neuts)

numpy.ndarray

In [134]:
type(c)

numpy.ndarray

In [142]:
all_sets.shape

(63, 4)

In [155]:
%%time 
b = [i for i in range(10000000)]

CPU times: user 445 ms, sys: 185 ms, total: 629 ms
Wall time: 630 ms
