In [1]:
import sys
import copy
import emcee
import corner
import numpy as np
import matplotlib.pyplot as plt
from mods import prep, plotter
from scipy import optimize
%matplotlib inline
%load_ext autoreload

sys.path.append('./ligbind/')
import ligbind

In [2]:
#vary all Wym model parameters
#variance weighted by y-value (not y squared)
def lnlik(allfit,data,ligs):
    datac = np.concatenate(data)
    modparms = allfit[0:4]
    rtots = allfit[4:-1]
    f = allfit[-1]
    model = ligbind.models.wymfunc(modparms,ligs,rtots)
    invsig2 = 1.0/np.square(f * np.sqrt(model))
    return -0.5*(np.sum((datac-model)**2*invsig2 - np.log(invsig2)))

In [3]:
#uniform prior based on bounds
def lnpri(allfit,bounds):
    assert len(bounds) == len(allfit)
    if all([bounds[i][0] <= allfit[i] <= bounds[i][1] for i in range(len(bounds))]) is True:
        return 0.0
    else:
        return -np.inf

In [4]:
def lnprob(allfit,bounds,data,ligs):
    lp = lnpri(allfit,bounds)
    if not np.isfinite(lp):
        return -np.inf
    return lp + lnlik(allfit,data,ligs)

In [5]:
bnds = ((4.6, 4.6),
        (5.3, 5.3),
        (0.34, 0.34),
        (530.0, 530.0),
        (0.0, 1.0),
        (0.0, 1.0),
        (0.0, 1.0),
        (0.0, 1.0),
        (0.0, 1.0),
        (0.0, 1.0),
        (0.0001, 0.1))

In [6]:
guess = np.array([4.60,
                  5.30,
                  3.40e-01,
                  5.30e+02,
                  5.70e-04,
                  1.02e-03,
                  2.18e-03,
                  2.85e-03,
                  5.48e-03,
                  1.06e-02,
                  0.02])

In [7]:
est = np.array([5.70E-04,
                1.02E-03,
                2.18E-03,
                2.85E-03,
                5.48E-03,
                1.06E-02])

In [47]:
np.float64(est/10.)

array([  5.70000000e-05,   1.02000000e-04,   2.18000000e-04,
         2.85000000e-04,   5.48000000e-04,   1.06000000e-03])

In [48]:
np.float64(est*10.)

array([ 0.0057,  0.0102,  0.0218,  0.0285,  0.0548,  0.106 ])

In [46]:
tuple(i for i in zip(np.float64(rtlo.tolist()),np.float64(rthi.tolist())))

((5.6999999999999996e-05, 0.0057000000000000002),
 (0.00010200000000000001, 0.010200000000000001),
 (0.00021800000000000001, 0.0218),
 (0.00028499999999999999, 0.028500000000000001),
 (0.00054799999999999998, 0.054799999999999995),
 (0.00106, 0.106))

In [22]:
[type(i) for i in rtlo]

[numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64,
 numpy.float64]

In [36]:
bnds = ((4.6, 4.6),
        (5.3, 5.3),
        (0.34, 0.34),
        (530.0, 530.0),
        (5.6999999999999996e-05, 0.0057),
        (0.00010200000000000001, 0.0102),
        (0.000218, 0.0218),
        (0.000285, 0.0285),
        (0.000548, 0.054799999999999995),
        (0.00106, 0.106),
        (0.0001, 0.1))

In [37]:
bnds

((4.6, 4.6),
 (5.3, 5.3),
 (0.34, 0.34),
 (530.0, 530.0),
 (5.6999999999999996e-05, 0.0057),
 (0.00010200000000000001, 0.0102),
 (0.000218, 0.0218),
 (0.000285, 0.0285),
 (0.000548, 0.054799999999999995),
 (0.00106, 0.106),
 (0.0001, 0.1))

In [50]:
thing = np.float64(bnds)

In [51]:
tuple(thing)

(array([ 4.6,  4.6]),
 array([ 5.3,  5.3]),
 array([ 0.34,  0.34]),
 array([ 530.,  530.]),
 array([  5.70000000e-05,   5.70000000e-03]),
 array([ 0.000102,  0.0102  ]),
 array([ 0.000218,  0.0218  ]),
 array([ 0.000285,  0.0285  ]),
 array([ 0.000548,  0.0548  ]),
 array([ 0.00106,  0.106  ]),
 array([ 0.0001,  0.1   ]))